# Terraform Provider testing workflow.
name: lints

# This GitHub action runs your tests for each pull request and push.
# Optionally, you can turn it on using a schedule for regular testing.
on:
  pull_request:
  push:

# Testing only needs permissions to read the repository contents.
permissions:
  contents: read

jobs:
  # Ensure project builds before running testing matrix
  app:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: sudo apt-get install -y libseccomp-dev pkg-config
      - run: go mod download
      - name: Run linters
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest